---
abstract: "Creates a temporary instance of OpenLDAP's slapd daemon to run tests against."
author:
  - 'David Dick <ddick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-OpenLDAP
no_index:
  directory:
    - t
    - inc
requires:
  Config: '0'
  Data::UUID: '0'
  DirHandle: '0'
  English: '0'
  File::Temp: '0'
  FileHandle: '0'
  Net::LDAP: '0'
  POSIX: '0'
  Test::More: '0'
  URI::Escape: '0'
version: '0.71'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
